name: 'Armbian/build'
author: "Stefan Dej"
inputs:
  board:
    description: 'Armbian board name'
    required: true
    type: string
  release-id:
    description: 'ID from github release'
    required: false
    type: string
secrets:
  github-taken:
    required: true

runs:
  using: "composite"
  steps:
    - name: Runner prepare
      uses: meteyou/armbian-builds/actions/runner-prepare@test-self-hosted

    - name: Checkout armbian/build
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: armbian/build
        ref: master
        path: build

    - name: Checkout meteyou/armbian-builds
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: meteyou/armbian-builds
        path: scripts

    - name: Copy templates
      run: |
        mkdir -p build/userpatches
        cp scripts/configs/* build/userpatches/

    - name: Build Image
      shell: bash
      run: |
        cd ./build
#          ./compile.sh BOARD=${{ inputs.board }}

    - name: Upload Image to Release
      if: inputs.release-id != '' && secrets.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: ./build/output/images/*
        draft: false

    - name: Rollback release
      if: failure() && inputs.release-id != '' && secrets.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
