name: 'Armbian/build'
author: 'Stefan Dej'
description: 'Build armbian images'
inputs:
  board:
    description: 'Armbian board name'
    required: true
  release-id:
    description: 'ID from github release'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Runner prepare
      uses: meteyou/armbian-builds/actions/runner-prepare@test-self-hosted

    - name: Checkout armbian/build
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: armbian/build
        ref: master
        path: build

    - name: Checkout meteyou/armbian-builds
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: meteyou/armbian-builds
        path: scripts

    - name: Copy templates
      shell: bash
      run: |
        mkdir -p build/userpatches
        cp scripts/configs/* build/userpatches/

    - name: Build Image
      shell: bash
      run: |
        cd ./build
#       ./compile.sh BOARD=${{ inputs.board }}

    - name: Upload Image to Release
      if: inputs.release-id != ''
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ inputs.release-id }}
        file: ./build/output/images/*
        draft: false

    - name: Rollback release
      if: failure() && inputs.release-id != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ inputs.release-id }}
