name: 'Armbian/build'
author: 'Stefan Dej'
description: 'Build armbian images'
inputs:
  configfile:
    description: 'Config file name'
    required: true
  release-id:
    description: 'ID from github release'
    required: false
  github-token:
    description: 'github token'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Runner prepare
      uses: meteyou/armbian-builds/actions/runner-prepare@test-self-hosted

    - name: Checkout armbian/build
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: armbian/build
        ref: master
        path: build

    - name: Checkout meteyou/armbian-builds
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: meteyou/armbian-builds
        path: own-configs

#    - name: Copy templates
#      shell: bash
#      run: |
#        mkdir -p build/userpatches
#        cp scripts/configs/* build/userpatches/

    - name: Read board config
      id: config
      shell: bash
      run: |
        source ./own-configs/configs/config-default.conf
        source ./own-configs/configs/board-${{ inputs.configfile }}.conf
        
        echo $BOARD

#    - name: Build Image
#      shell: bash
#      run: |
#        cd ./build
#       ./compile.sh BOARD=${{ inputs.board }}


    - name: Fix userrights
      shell: bash
      run: |
        WORKSPACE=$(echo ${{ github.workspace }})
        sudo chown -R $USER:$USER $WORKSPACE/build/. || true
        sudo df

#    - name: Upload Image to Release
#      if: inputs.release-id != '' && inputs.github-token != ''
#      uses: xresloader/upload-to-github-release@v1
#      env:
#        GITHUB_TOKEN: ${{ inputs.github-token }}
#      with:
#        release_id: ${{ inputs.release-id }}
#        file: ./build/output/images/*
#        draft: false
