name: 'Armbian/build'
author: 'Stefan Dej'
description: 'Armbian Linux build framework from amazingfate/armbian-compile-action'
inputs:
  configfile:
    description: 'Config file name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get more space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 30720
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: build-configs

    - name: Read configs
      id: config
      shell: bash
      run: |
        source ./build-configs/configs/config-default.conf
        source ./build-configs/configs/board-${{ inputs.configfile }}.conf
        
        echo "armbian_repository=${ARMBIAN_REPOSITORY}" >> $GITHUB_OUTPUTS
        echo "armbian_branch=${ARMBIAN_BRANCH}" >> $GITHUB_OUTPUTS

    - name: Checkout armbian Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: ${{ steps.config.outputs.armbian_repository }}
        ref: ${{ steps.config.outputs.armbian_branch }}
        path: build

    - name: Build Image
      shell: bash
      run: |
        cd ./build
        sed -i -e 's/-it//g' ./config/templates/config-docker.conf
        docker_tag=$(cat VERSION|cut -d "-" -f1)
        docker_tag_in_repo=${docker_tag:0:5}
        docker pull ghcr.io/armbian/build:${docker_tag_in_repo}-amd64
        docker image tag ghcr.io/armbian/build:${docker_tag_in_repo}-amd64 armbian:$(cat VERSION)
        ./compile.sh docker \
          BOARD="${BOARD}" \
          RELEASE="${RELEASE}" \
          BRANCH="${BRANCH}" \
          BUILD_DESKTOP="${BUILD_DESKTOP}" \
          BUILD_MINIMAL="${BUILD_MINIMAL}" \
          KERNEL_ONLY="${KERNEL_ONLY}" \
          KERNEL_CONFIGURE="${KERNEL_CONFIGURE}" \
          BOOTFS_TYPE="${BOOTFS_TYPE}"\
          COMPRESS_OUTPUTIMAGE="${COMPRESS_OUTPUTIMAGE}" \
          REPOSITORY_INSTALL="${REPOSITORY_INSTALL}"
