name: 'Armbian/build'
description: 'Armbian Linux build framework from amazingfate/armbian-compile-action'

on:
  workflow_call:
    inputs:
      board:
        description: 'Armbian board name'
        required: true
      release-id:
        description: 'ID from github release'
        required: false
      github-token:
        description: 'Token to upload the Image to the release'
        required: false

jobs:
  build_armbian:
    name: Build Armbian
    runs-on: self-hosted
    steps:
      - name: Checkout armbian/build
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          ref: master
          path: build

      - name: Build Image
        shell: bash
        run: |
          cd ./build
          ./compile.sh \
          BOARD=${{ inputs.board }} \
          BRANCH=edge \
          RELEASE=bullseye \
          BUILD_MINIMAL=yes \
          BUILD_DESKTOP=no \
          KERNEL_ONLY=no \
          KERNEL_CONFIGURE=no \
          BOOTFS_TYPE=fat \
          COMPRESS_OUTPUTIMAGE=sha,gpg,xz

      - name: Upload Image to Release
        if: inputs.release-id != '' && inputs.github-token != ''
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
        with:
          release_id: ${{ inputs.release-id }}
          file: ./build/output/images/*
          draft: false

      - name: Rollback release
        if: failure() && inputs.release-id != '' && inputs.github-token != ''
        uses: author/action-rollback@stable
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
        with:
          release_id: ${{ inputs.release-id }}
