name: Build Train Self Hosted
on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/BuildTrainSelfHosted.yml"
      - "actions/build-image/action.yml"
      - "actions/runner-prepare/action.yml"
      - "configs/config-default.conf"
  workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
  group: ci-buildtrain-self-hosted-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  prepare_release:
    name: Create Release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'

      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.time.outputs.time }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
    outputs:
      release_id: ${{ steps.release.outputs.id }}

  build:
    name: Build Images
    needs: prepare_release
    strategy:
      fail-fast: false
      matrix:
#        BOARD: [ radxa-zero, orangepizero ]
        BOARD: [ radxa-zero, orangepi3-lts, orangepi4-lts, orangepizero, orangepizero2, rpi4b ]
    runs-on: fast-runner
    steps:
      - name: Build image
        uses: meteyou/armbian-builds/actions/build-image@test-self-hosted
        with:
          board: ${{ matrix.BOARD }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
