name: Build Train Self Hosted
on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/BuildTrainSelfHosted.yml"
      - "actions/build-image/action.yml"
      - "actions/runner-prepare/action.yml"
      - "configs/config-default.conf"
  workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
  group: ci-buildtrain-self-hosted-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  setup:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      configfiles: ${{ steps.set-matrix.outputs.configfiles }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Matrix
        id: set-matrix
        run: |
          JSON=$(find ${{ github.workspace }}/configs -type f -name "board-*.conf" -printf '%f\n' | sed 's#board-##;s#.conf##' | jq -R -s -c 'split("\n")[:-1]')
          echo $JSON
          echo $(find ${{ github.workspace }}/configs -type f -name "board-*.conf" -printf '%f\n' | sed 's#board-##;s#.conf##')
          echo "::set-output name=configfiles::${JSON}"
          
          cd ${{ github.workspace }}/configs
          echo "::set-output name=matrix::$(ls * | jq -R -s -c 'split("\n")[:-1]')"

  prepare_release:
    name: Create Release
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'

      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.time.outputs.time }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
    outputs:
      release_id: ${{ steps.release.outputs.id }}

  test_json:
    name: Test output
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: |
          echo ${{ needs.setup.outputs.configfiles }}
          echo ${{ needs.setup.outputs.matrix }}
          echo ${${{ fromJSON(needs.setup.outputs.configfiles) }}[0]}

  build:
    name: Build Images
    needs: prepare_release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Build image
        uses: meteyou/armbian-builds/actions/build-image@test-self-hosted
        with:
          configfile: ${{ matrix.board }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
